name: modexp
  
services:

  modexp-spring:
    container_name: modexp-spring
    build: modexp/.
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD

  modexp-pgadmin:
    container_name: modexp-pgadmin
    image: 'docker.io/dpage/pgadmin4:latest'
    ports:
      - "9876:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD

  modexp-db: 
    container_name: modexp-db
    build: postgres/.
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
